blank_issues_enabled: true
contact_links:
  - name: Ask a question ‚ùì
    url: https://github.com/jasontaylordev/Books.Prototype/discussions/new
    about: Ask a question or request support for using the template